// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shhkccidqvvrwgxlyvqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaGtjY2lkcXZ2cndneGx5dnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTE5MDksImV4cCI6MjA2NDI4NzkwOX0.Oi6CoH5pllOJMIZDvwHyocuAyWAQVNwqYfJt8KO-b-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);